name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Download and install JavaFX
      run: |
        mkdir -p $HOME/javafx-sdk
        cd $HOME/javafx-sdk
        wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
        unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
        export PATH_TO_FX=$HOME/javafx-sdk/javafx-sdk-21.0.2/lib

    - name: Build clean
      run: mvn clean
      working-directory: ES2_2023-2_DSMEditor/
      
    - name: Build install
      run: mvn install
      working-directory: ES2_2023-2_DSMEditor/
    
    - name: Build package
      run: mvn package
      working-directory: ES2_2023-2_DSMEditor/
    
    - name: Build run
      run: mvn javafx:run -Djavafx.path=$PATH_TO_FX -X
      working-directory: ES2_2023-2_DSMEditor/
      
    - name: Build test
      run: mvn clean test
      working-directory: ES2_2023-2_DSMEditor/

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
