name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build clean
      run: mvn clean
      working-directory: ES2_2023-2_DSMEditor/
      
    - name: Build install
      run: mvn install
      working-directory: ES2_2023-2_DSMEditor/
    
    - name: Build package
      run: mvn package
      working-directory: ES2_2023-2_DSMEditor/
    
    - name: Build test
      run: mvn clean test
      working-directory: ES2_2023-2_DSMEditor/
